CREATE TABLE service_requests (
  unique_key BIGINT PRIMARY KEY,
  created_date DATETIME,
  closed_date DATETIME,
  agency TEXT,
  agency_name TEXT,
  complaint_type TEXT,
  descriptor TEXT,
  location_type TEXT,
  incident_zip DOUBLE,
  incident_address TEXT,
  street_name TEXT,
  cross_street_1 TEXT,
  cross_street_2 TEXT,
  intersection_street_1 TEXT,
  intersection_street_2 TEXT,
  address_type TEXT,
  city TEXT,
  landmark TEXT,
  facility_type TEXT,
  status TEXT,
  due_date TEXT,
  resolution_description TEXT,
  resolution_action_updated_date TEXT,
  community_board TEXT,
  bbl DOUBLE,
  borough TEXT,
  latitude DOUBLE,
  longitude DOUBLE,
  location TEXT
);
