name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nyc311_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uuser -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest selenium pymysql sqlalchemy pandas

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          sleep 20

      - name: Run ETL on small fixture CSV
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: nyc311_db
        run: |
          python etl/etl.py --csv tests/fixtures/311_sample.csv --chunksize 2000

      - name: Start Flask app in background
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: nyc311_db
        run: |
          nohup python app/main.py &
          sleep 10

      - name: Run Selenium tests
        run: pytest -q --maxfail=1 --disable-warnings -v
